version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_build:
      - mkdir --parents _readthedocs/htmlzip
      - cp --recursive _readthedocs/html _readthedocs/$READTHEDOCS_PROJECT
      - cd _readthedocs ; zip --recurse-path --symlinks htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
- htmlzip




