version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_build:
      # This is a small hack to avoid this issue:
      # https://github.com/readthedocs/readthedocs.org/issues/9179
      - mkdir --parents _readthedocs/htmlzip
      - cp --recursive _readthedocs/html _readthedocs/$READTHEDOCS_PROJECT
      - cd _readthedocs ; zip --recurse-path --symlinks htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT
      
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  
formats:
- htmlzip



